export const GET_CATAGORY_SERVICE_REQUEST = "GET_CATAGORY_SERVICE_REQUEST";
export const GET_CATAGORY_SERVICE_SUCCESS = "GET_CATAGORY_SERVICE_SUCCESS";
export const GET_CATAGORY_SERVICE_FAIL = "GET_CATAGORY_SERVICE_FAIL";
